// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: thumb.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Thumbnails_Get_FullMethodName = "/Thumbnails/Get"
)

// ThumbnailsClient is the client API for Thumbnails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThumbnailsClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type thumbnailsClient struct {
	cc grpc.ClientConnInterface
}

func NewThumbnailsClient(cc grpc.ClientConnInterface) ThumbnailsClient {
	return &thumbnailsClient{cc}
}

func (c *thumbnailsClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Thumbnails_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThumbnailsServer is the server API for Thumbnails service.
// All implementations must embed UnimplementedThumbnailsServer
// for forward compatibility
type ThumbnailsServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedThumbnailsServer()
}

// UnimplementedThumbnailsServer must be embedded to have forward compatible implementations.
type UnimplementedThumbnailsServer struct {
}

func (UnimplementedThumbnailsServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedThumbnailsServer) mustEmbedUnimplementedThumbnailsServer() {}

// UnsafeThumbnailsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThumbnailsServer will
// result in compilation errors.
type UnsafeThumbnailsServer interface {
	mustEmbedUnimplementedThumbnailsServer()
}

func RegisterThumbnailsServer(s grpc.ServiceRegistrar, srv ThumbnailsServer) {
	s.RegisterService(&Thumbnails_ServiceDesc, srv)
}

func _Thumbnails_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbnailsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Thumbnails_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbnailsServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Thumbnails_ServiceDesc is the grpc.ServiceDesc for Thumbnails service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Thumbnails_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Thumbnails",
	HandlerType: (*ThumbnailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Thumbnails_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thumb.proto",
}
